name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run on every push on the master branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Generate the Isometric Calendar (Using GITHUB_TOKEN)
      - name: Generate Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Surjoyday
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          filename: isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # 2. Generate the Reactions Chart (Using GITHUB_TOKEN)
      - name: Generate Reactions
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Surjoyday
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          filename: reactions.svg
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
